CREATE TABLE IF NOT EXISTS connector_runtimes (
    key TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    management_mode TEXT NOT NULL,
    bundled_version TEXT NOT NULL,
    active_version TEXT NOT NULL,
    active_path TEXT NOT NULL,
    custom_path TEXT,
    latest_version TEXT,
    latest_asset_url TEXT,
    latest_checked_at TEXT,
    update_status TEXT NOT NULL,
    pending_version TEXT,
    pending_path TEXT,
    progress_percent INTEGER,
    progress_detail TEXT,
    last_error TEXT,
    updated_at TEXT NOT NULL,
    CHECK (management_mode IN ('managed', 'custom'))
);
